name: Vincent Palma
favicon: null
layout_spectrum: 0.89475
typography_spectrum: 1
title: Vincent Palma Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9013708827551454
  lightness: 0.9133781967684627
  saturation: 0.3683014598209411
  rhythmicContrast: 0.22600354813039303
purpose: []
